### ISSUE TITLE
Toy-Experiment

### ISSUE THREAD

**Issue by vincehass** [dbsxodud-11/logit-gfn#1]
Hi,
I am reproducing your work, but couldn't find the toy experiment. Is it possible to include it in the repo?
Thanks so much!

**Comment by dbsxodud-11** [comment]
Hi, sorry for the late response.
I just attached the code for gridworld experiments on the `grid` branch. It is based on original gflownet code: https://github.com/GFNOrg/gflownet.

Best regards,
